In [1]:
#импортируем нужный алгоритм
from sklearn.decomposition import PCA, TruncatedSVD
import numpy as np
import pandas as pd
from numpy.linalg import eig
#определяем метод главных компонент с двумя компонентами

In [22]:
a = np.array([3,4,1])
b = np.array([1,6,2])
#df = pd.DataFrame(df, columns  = ['x1','x2','x3'])
#@df_std  = (df - df.mean()) / (df.std())
cov_mat = np.cov(a,b)
cov_mat
round(cov_mat.sum(), 2)

np.float64(14.33)

In [ ]:
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

df_std = pd.DataFrame(df_std)


In [35]:
#определяем метод главных компонент с двумя компонентами
pca = PCA(n_components=0.90)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(df_std)
pca.n_components_

np.int64(3)

In [3]:
a = np.array([[2,0,-1],
               [0,2,-1],
               [-1,-1,1]])
eigenvalues, eigenvectors = eig(a)

In [ ]:
print(f'Eigenvalues = {eigenvalues}') 
print(f'Eigenvectors: \n{eigenvectors}')

Eigenvalues = [-2.22044605e-16  2.00000000e+00  3.00000000e+00]
Eigenvectors: 
[[ 4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  5.52174535e-16 -5.77350269e-01]]


: 

In [5]:
# n_components — размерность нового пространства, n_iter — количество итераций
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=42)
# обучаем модель на данных X
svd.fit(a)
# применяем уменьшение размерности к матрице X
transformed = svd.transform(a)